config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "ui", to: "pages#ui"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  authenticated :user, ->(u) { u.tutor?} do
    root to: "users#home", as: :tutor_root
  end

  authenticated :user, ->(u) { u.patient?} do
    root to: "takes#index", as: :patient_root
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"

  resources :patients, only: [:new, :create, :edit, :update, :destroy] do
    resources :planifications, only: %i[index new create]
    member do
      get 'cam'
    end
    resources :takes, only: %i[index]
    resources :patient_takes, only: %i[index]
    resources :patient_histo, only: %i[index create]
  end

  resources :planifications, only: %i[edit update destroy] do
    member do
      get 'confirm'
    end
    collection do
      post 'photo'
    end
  end

  resources :tutor_patients, only: [:show] do
    resources :chats, only: [:create]
  end

  resources :takes, only: [] do
    member do
      get 'cam_patient'
      post 'photo'
      patch 'taken'
    end
  end

end

app/models/tutor_patient.rb
class TutorPatient < ApplicationRecord
  belongs_to :tutor, class_name: 'User'
  belongs_to :patient, class_name: 'User'
  has_many :chats
end

app/controllers/tutor_patients_controller.rb
class TutorPatientsController < ApplicationController
  def show
    @relation = TutorPatient.find(params[:id])
    @chat= Chat.new
    if current_user.tutor?
      @other_user = @relation.patient
      @writer=current_user
    else
      @writer = current_user
      @other_user=@relation.tutor
    end
  end
end

app/views/tutor_patients/show.html.erb
<div class="default_card">
  <div class="chat">
    <h1 class="text-center pt-1 pb-4">Discussion avec <%= @other_user.first_name %></h1>
    <%= turbo_stream_from "chat_#{@relation.id}_chats" %>
    <div id="chats" class="messages">
      <% @relation.chats.each do |chat| %>
        <%= render "components/chat", chat: chat, user: current_user %>
      <% end %>
    </div>
  </div>

  <%= simple_form_for [@relation, @chat], url: tutor_patient_chats_path(@relation),
    html: {class: "d-flex", data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }, autocomplete: "off"} do |f|
  %>
    <%# <% other_user = current_user == @booking.restaurant.user ? @booking.user : @booking.restaurant.user %>
    <%= f.input :message,
      label: false,
      placeholder: "Ecrire à #{@other_user.first_name}",
      wrapper_html: {class: "flex-grow-1"}
    %>
    <%= f.submit "Envoyer", class: "btn btn-primary text-white mb-3" %>
  <% end %>
</div>

<%  if @writer.tutor? %>
  <%= link_to patient_patient_takes_path(@relation.patient_id) do %>
    <%= render "components/back_button", symbol: raw('<i class="fa-solid fa-angle-left"></i>') %>
  <% end %>
<% else  %>
  <%= link_to patient_root_path do %>
    <%= render "components/back_button", symbol: raw('<i class="fa-solid fa-angle-left"></i>') %>
  <% end %>
<% end %>