config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "ui", to: "pages#ui"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  authenticated :user, ->(u) { u.tutor?} do
    root to: "users#home", as: :tutor_root
  end

  authenticated :user, ->(u) { u.patient?} do
    root to: "takes#index", as: :patient_root
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"

  resources :patients, only: [:new, :create, :edit, :update, :destroy] do
    resources :planifications, only: %i[index new create]
    member do
      get 'cam'
    end
    resources :takes, only: %i[index]
    resources :patient_takes, only: %i[index]
    resources :patient_histo, only: %i[index create]
  end

  resources :planifications, only: %i[edit update destroy] do
    member do
      get 'confirm'
    end
    collection do
      post 'photo'
    end
  end

  resources :tutor_patients, only: [:show] do
    resources :chats, only: [:create]
  end

  resources :takes, only: [] do
    member do
      get 'cam_patient'
      post 'photo'
      patch 'taken'
    end
  end

end

app/models/planification.rb
class Planification < ApplicationRecord
  belongs_to :medication
  belongs_to :dosage
  belongs_to :patient, :class_name => 'User'
  has_many :plan_takings
  has_many :taking_periods, through: :plan_takings
  accepts_nested_attributes_for :plan_takings
  has_many :takes, dependent: :destroy
  has_one_attached :photo

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :start_date, :end_date, presence: true
  validates :end_date, comparison: { greater_than_or_equal_to: :start_date }
  validates :frequency_days, presence: true, numericality: { only_integer: true, greater_than: 0 }
  # after_save :set_takes_job
  after_commit :set_takes_job, on: %i[create update]

  private

  def set_takes_job
    TakesCreationJob.perform_later(self)
  end
end

app/controllers/planifications_controller.rb
class PlanificationsController < ApplicationController
  before_action :set_patient, except: %i[destroy]
  before_action :set_planification, only: %i[confirm edit update destroy]
  require 'cloudinary'
  require 'cloudinary/uploader'
  require 'cloudinary/utils'


  def index
    @planifications = Planification.where(patient_id: @patient.id)
  end

  def photo
    base64_image = request.body.read
    open_ai_service = OpenAiSvc.new
    reponse = open_ai_service.analyser_boite(base64_image)

    ##Traitement du medicament (Ajout dans la db si non trouvé)
    if reponse != ""
      medic_name = reponse['name'].upcase + " " + reponse['dosage']
      type_medic = reponse['type']
      medic = Medication.find_or_create_by(name: medic_name)

      rechtype = type_medic.downcase.singularize + "(s)"
      dosage_type = Dosage.find_by(label: rechtype)
      if dosage_type == nil
        dosage_type = ""
      end

      respond_to do |format|
        format.json { render json: { message: "Médicament à planifier.", medication: medic, type: dosage_type }, status: :ok }
      end
    else
      # Fail lors de la récupération du médic
      respond_to do |format|
        format.json { render json: { error: "NOT_FOUND" }, status: :ok }
      end
    end
  end

  def new
    @planification = Planification.new
    @planification.patient_id = @patient.id
  end

  def create

    @planification = Planification.new(planification_params)
    @planification.patient_id = @patient.id
    if @planification.photo.attached? #=> true/false
      @planification.photo.purge
    end
    # photo=params[:file]
    # cloudinary_response = Cloudinary::Uploader.upload(photo.tempfile.path)

    @planification.photo.attach(params[:file])

    if @planification.save!
      respond_to do |format|
        # format.html { redirect_to patient_planifications_path(@patient), notice: "Planification created successfully." }
        format.json { render json: { message: "Planification created successfully.", planification: @planification }, status: :created }
        # data-camera-url-value=<%="#{confirm_planification_path(@planification)}
      end
    else
      respond_to do |format|
        # format.html { redirect_to patient_planifications_path(@patient), notice: "Planification created successfully." }
        format.json { render json: { errors: "Planif failed", planification: @planification }, status: :created }
      end
    end
  end

  def edit
  end

  def update
    if @planification.update!(planification_params)
      respond_to do |format|
        format.json { render json: { message: "Planification updated successfully.", planification: @planification } }
      end
    else
      respond_to do |format|
        format.json { render json: { errors: "Planif failed", planification: @planification } }
      end
    end
  end

  def destroy
    @patient = @planification.patient
    Planification.destroy(@planification.id)
    redirect_to patient_planifications_path(@patient)
  end

  def confirm
  end

  private

  def set_patient
    if params[:patient_id]
      @patient = User.find(params[:patient_id])
    else
      @patient = current_user
    end
  end

  def planification_params
    params.require(:planification).permit(:photo, :medication_id, :description, :start_date, :end_date, :dosage_id, :frequency_days, :quantity, :patient_id, taking_period_ids:[])
 end

 def set_planification
  @planification = Planification.find(params[:id])
 end
end

app/views/planifications/confirm.html.erb
<%= render "components/confirm_planification" %>

app/views/planifications/create.html.erb
<h1>Planifications#create</h1>
<p>Find me in app/views/planifications/create.html.erb</p>

app/views/planifications/destroy.html.erb
<h1>Planifications#destroy</h1>
<p>Find me in app/views/planifications/destroy.html.erb</p>

app/views/planifications/edit.html.erb
<div class="custom-confirm" data-controller="edit-planification" data-edit-planification-url-value=<%="#{planification_path(@planification)}"%> data-edit-planification-cancel-value=<%="#{patient_planifications_path(@planification.patient.id)}"%>>
  <strong><i class="fa-solid fa-pills custom-icon"></i></strong>
  <h1>Modifier la prescription</h1>
  <div class="form_card m-4">
    <div class="form_inputs", data-controller="checkbox">
      <%= simple_form_for @planification, url:  planification_path(@planification), html: { data: { edit_planification_target: 'form'} } do |f| %>
        <% if @planification.photo.key != nil %>
          <%= cl_image_tag @planification.photo.key, class: "size" %>
        <% end %>
        <div class="custom-title">
        <h2><%= @planification.medication.name %></h2>
        </div>
        <div class="posotity">
          <%= f.input :quantity, label: "Quantité :", input_html: { min: 0} %>
          <%= f.association :dosage, label_method: :label, label: "Posologie :" %>
        </div>
        <%= f.input :frequency_days, label: "Intervalle de prises en jours :", input_html: { min: 0} %>
        <div data-controller="flatpickr" class="center-calendar">
          <label class="form-label range required" for="range_range">Dates de prescription : <abbr title="required">*</abbr></label>
          <input class="form-control string optional d-none" data-target="flatpickr.rangeDate" id="range_range" type="text" name="planification[range_date]">
          <%= f.input :start_date, label: false, as: :string, required: false,
                      input_html: {  data: { target: "flatpickr.startDate" }, value: @planification.start_date.strftime('%d/%m/%Y'), id: "range_start", class: "d-none" } %>
          <%= f.input :end_date, label: false, as: :string, required: false,
                      input_html: {  data: { target: "flatpickr.endDate" }, value: @planification.end_date.strftime('%d/%m/%Y') , id: "range_end", class: "d-none" } %>
        </div>

        <div class="check-boxes-container">
          <%= f.association :taking_periods, as: :check_boxes,
                        label: "Moments de la journée :",
                        label_method: :label,
                        value_method: :id,
                        input_html: { data: { action: "click->checkbox#toggle", checkbox_target: "checkbox" } },
                        item_label_class: 'checkbox-item toggle-label labels col-sm' %>
        </div>
        <%= f.input :description, as: :text, input_html: { class: "text-area", :rows => 4 } %>
        <% end %>
    </div>
  </div>
  <div class="buttons_double">
    <button data-action="click->edit-planification#cancel"><i class="fa-solid fa-chevron-left"></i> Retour</button>
    <button data-action="click->edit-planification#submitForm"><i class="fa-solid fa-check"></i> Enregistrer</button>
  </div>
</div>

app/views/planifications/index.html.erb
<h2 class="text-center" style="margin-top: 20px;">Prescriptions pour <%= @patient.first_name %></h2><hr>

<% if current_user.tutor? %>
  <div>
  <%= link_to cam_patient_path(@patient.id) do%>
    <%= render "components/button_edit", content: "Nouvelle prescription" %>
  <% end %>
  </div>
<% end %>

<%= render "components/accordion_card", elements: @planifications %>

<%= link_to patient_patient_takes_path do %>
  <%= render "components/back_button", symbol: raw('<i class="fa-solid fa-angle-left"></i>') %>
<% end %>

app/views/planifications/new.html.erb
<h1>Planifications#new</h1>
<p>Find me in app/views/planifications/new.html.erb</p>

<%# form planification %>
<%# Display photo planification, then selection of the drug, then form planification,
use js to display one at a time? %>

<%= render "form_planification", partial: [@patient, @planification]  %>

app/views/planifications/update.html.erb
<h1>Planifications#update</h1>
<p>Find me in app/views/planifications/update.html.erb</p>