config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "ui", to: "pages#ui"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  authenticated :user, ->(u) { u.tutor?} do
    root to: "users#home", as: :tutor_root
  end

  authenticated :user, ->(u) { u.patient?} do
    root to: "takes#index", as: :patient_root
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"

  resources :patients, only: [:new, :create, :edit, :update, :destroy] do
    resources :planifications, only: %i[index new create]
    member do
      get 'cam'
    end
    resources :takes, only: %i[index]
    resources :patient_takes, only: %i[index]
    resources :patient_histo, only: %i[index create]
  end

  resources :planifications, only: %i[edit update destroy] do
    member do
      get 'confirm'
    end
    collection do
      post 'photo'
    end
  end

  resources :tutor_patients, only: [:show] do
    resources :chats, only: [:create]
  end

  resources :takes, only: [] do
    member do
      get 'cam_patient'
      post 'photo'
      patch 'taken'
    end
  end

end

app/controllers/patient_takes_controller.rb
class PatientTakesController < ApplicationController
  before_action :set_patient, only: %i[index]

  def index
    @takes = Take.current_take(@patient)
    if current_user.tutor?
      @tutor_patient_relation = TutorPatient.where(["patient_id = ? and tutor_id = ?", @patient.id, current_user.id])
    else
      @tutor_patient_relation = TutorPatient.where(patient_id: @patient.id)
    end
  end



  private

  def set_patient
    if params[:patient_id]
      @patient = User.find(params[:patient_id])
    else
      @patient = current_user
    end
  end
end

app/views/patient_takes/index.html.erb
<% if current_user.tutor? %>
  <div class="default_card">
    <h2 class="patient-full-name"><%= "#{@patient.first_name} #{@patient.last_name}" %></h2>
    <hr>
    <div class="row d-flex justify-content-center">
      <div class="col-auto">
        <%= link_to edit_patient_path(@patient.id) do %>
          <%= render "components/little_buttons", content: "Editer" %>
        <% end %>
      </div>
      <div class="col-auto">
        <%= link_to patient_patient_histo_index_path(@patient) do%>
          <%= render "components/little_buttons", content: "Historique" %>
        <% end %>
      </div>
    </div>
      <div class="col-auto">
        <%= link_to patient_planifications_path(@patient.id) do%>
          <%= render "components/button", content: "Voir les prescriptions" %>
        <% end %>
      </div>
  </div>
<% end %>

<h2 class="text-center" style="margin-top: 20px;">Prises de médicaments du jour</h2><hr>

<% if current_user.tutor? %>
  <div>
    <%= link_to cam_patient_path(@patient.id) do%>
      <%= render "components/button_edit", content: "Nouvelle prescription" %>
    <% end %>
  </div>
<% end %>

<%= render "components/accordion_card_tutor_takes", elements: @takes %>

<%= link_to tutor_root_path do %>
  <%= render "components/back_button", symbol: raw('<i class="fa-solid fa-angle-left"></i>') %>
<% end %>

<%= link_to tutor_patient_path(@tutor_patient_relation.ids) do %>
  <%= render "components/chat_button" %>
<% end %>